name: Makefile CI

on:
  push:
    branches: [ "action" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@action
    
    - name: Compile gencass
      run: cd gencass && make cass
